import type { GameConfig, ItemDef } from './types';

/**
 * Catálogo por defecto de "El Valle".
 * - Los valores globales se pueden sobrescribir con game.config.json (ver README).
 * - Los valores de `tuning` también se pueden ajustar por servidor con /ajustes.
 */

const items: ItemDef[] = [
  // ── Huerta del Valle ──────────────────────────────────────────────
  { id: 'zanahoria', name: 'Zanahoria', emoji: '🥕', category: 'cultivo', rarity: 'comun', sellPrice: 6, description: 'Crujiente y fiel. La base de toda huerta.' },
  { id: 'papa', name: 'Papa', emoji: '🥔', category: 'cultivo', rarity: 'comun', sellPrice: 5, description: 'Nunca falta en la olla del valle.' },
  { id: 'lechuga', name: 'Lechuga', emoji: '🥬', category: 'cultivo', rarity: 'comun', sellPrice: 7, description: 'Fresca, si la cosechás a tiempo.' },
  { id: 'ajo', name: 'Ajo morado', emoji: '🧄', category: 'cultivo', rarity: 'poco_comun', sellPrice: 18, description: 'Aroma intenso, precio decente.' },
  { id: 'trebol', name: 'Trébol de cuatro hojas', emoji: '🍀', category: 'cultivo', rarity: 'raro', sellPrice: 220, description: 'Dicen que trae suerte a quien lo vende.' },
  // ── Invernadero ───────────────────────────────────────────────────
  { id: 'tomate', name: 'Tomate perita', emoji: '🍅', category: 'cultivo', rarity: 'comun', sellPrice: 14, description: 'Maduro bajo vidrio.' },
  { id: 'pimiento', name: 'Morrón', emoji: '🫑', category: 'cultivo', rarity: 'comun', sellPrice: 16, description: 'Verde, rojo o amarillo según el humor del invernadero.' },
  { id: 'frutilla', name: 'Frutilla', emoji: '🍓', category: 'cultivo', rarity: 'poco_comun', sellPrice: 38, description: 'Dulce y delicada.' },
  { id: 'orquidea', name: 'Orquídea nocturna', emoji: '🌺', category: 'cultivo', rarity: 'raro', sellPrice: 260, description: 'Florece solo cuando nadie mira.' },
  { id: 'semilla_ambar', name: 'Semilla de ámbar', emoji: '🟠', category: 'reliquia', rarity: 'epico', sellPrice: 1400, description: 'Una semilla fosilizada que todavía late.' },
  // ── Terrazas de Altura ────────────────────────────────────────────
  { id: 'te_verde', name: 'Hojas de té', emoji: '🍵', category: 'cultivo', rarity: 'comun', sellPrice: 30, description: 'Recogidas entre la niebla.' },
  { id: 'quinoa', name: 'Quinoa', emoji: '🌾', category: 'cultivo', rarity: 'comun', sellPrice: 26, description: 'Grano de montaña, resistente al frío.' },
  { id: 'cafe', name: 'Café de altura', emoji: '🫘', category: 'cultivo', rarity: 'poco_comun', sellPrice: 80, description: 'Tostado por el sol de las terrazas.' },
  { id: 'azafran', name: 'Azafrán', emoji: '🌸', category: 'cultivo', rarity: 'raro', sellPrice: 600, description: 'Tres hilos rojos que valen oro.' },
  { id: 'flor_altura', name: 'Flor de las nubes', emoji: '🏵️', category: 'reliquia', rarity: 'epico', sellPrice: 3200, description: 'Solo crece por encima de la niebla.' },
  // ── Bosque Frutal ─────────────────────────────────────────────────
  { id: 'manzana', name: 'Manzana roja', emoji: '🍎', category: 'cultivo', rarity: 'comun', sellPrice: 55, description: 'Del árbol más viejo del bosque.' },
  { id: 'nuez', name: 'Nuez', emoji: '🌰', category: 'cultivo', rarity: 'comun', sellPrice: 60, description: 'Las ardillas no están contentas.' },
  { id: 'miel', name: 'Miel silvestre', emoji: '🍯', category: 'cultivo', rarity: 'poco_comun', sellPrice: 170, description: 'Cuidado con las abejas.' },
  { id: 'trufa', name: 'Trufa negra', emoji: '🍄', category: 'cultivo', rarity: 'raro', sellPrice: 1300, description: 'Enterrada bajo raíces centenarias.' },
  { id: 'semilla_lunar', name: 'Semilla lunar', emoji: '🌙', category: 'reliquia', rarity: 'legendario', sellPrice: 12000, description: 'Abre el camino al Jardín Lunar.' },
  // ── Jardín Lunar ──────────────────────────────────────────────────
  { id: 'lirio_plata', name: 'Lirio de plata', emoji: '💮', category: 'cultivo', rarity: 'comun', sellPrice: 120, description: 'Brilla tenue bajo la luna.' },
  { id: 'calabaza_astral', name: 'Calabaza astral', emoji: '🎃', category: 'cultivo', rarity: 'poco_comun', sellPrice: 380, description: 'Tiene constelaciones en la cáscara.' },
  { id: 'fruto_eclipse', name: 'Fruto del eclipse', emoji: '🌑', category: 'cultivo', rarity: 'epico', sellPrice: 6500, description: 'Madura solo durante un eclipse.' },
  { id: 'brote_celestial', name: 'Brote celestial', emoji: '✨', category: 'reliquia', rarity: 'mitico', sellPrice: 60000, description: 'Nadie sabe de dónde vino.' },
  // ── Peces (precios por "agua": el valor sube con el nivel de pesca y con la rareza) ──
  // Aguas del arroyo (nivel 1)
  { id: 'mojarra', name: 'Mojarra', emoji: '🐟', category: 'pez', rarity: 'comun', sellPrice: 8, description: 'Pequeña y abundante.' },
  { id: 'bagrecito', name: 'Bagre de arroyo', emoji: '🐟', category: 'pez', rarity: 'comun', sellPrice: 10, description: 'Bigotes de sabio.' },
  { id: 'bota_vieja', name: 'Bota vieja', emoji: '🥾', category: 'chatarra', rarity: 'comun', sellPrice: 1, description: 'Alguien la extraña. O no.' },
  { id: 'cangrejo_rio', name: 'Cangrejo de río', emoji: '🦀', category: 'pez', rarity: 'poco_comun', sellPrice: 20, description: 'Pellizca fuerte.' },
  { id: 'trucha_arcoiris', name: 'Trucha arcoíris', emoji: '🐠', category: 'pez', rarity: 'raro', sellPrice: 50, description: 'Refleja todos los colores del arroyo.' },
  { id: 'bagre_albino', name: 'Bagre albino', emoji: '🐡', category: 'pez', rarity: 'epico', sellPrice: 160, description: 'Blanco como la luna. Los viejos pescadores lo llaman "el fantasma".' },
  { id: 'esturion_dorado', name: 'Esturión dorado', emoji: '🐠', category: 'pez', rarity: 'legendario', sellPrice: 560, description: 'Sus escamas parecen monedas antiguas.' },
  { id: 'koi_eclipse', name: 'Koi del eclipse', emoji: '🎏', category: 'pez', rarity: 'mitico', sellPrice: 2400, description: 'Mitad sol, mitad sombra. Aparece una vez cada muchas lunas.' },
  // Aguas del lago (nivel 8)
  { id: 'pejerrey', name: 'Pejerrey', emoji: '🐟', category: 'pez', rarity: 'comun', sellPrice: 22, description: 'Plateado y rápido.' },
  { id: 'carpa', name: 'Carpa', emoji: '🐟', category: 'pez', rarity: 'comun', sellPrice: 24, description: 'Vieja conocida del lago.' },
  { id: 'perca', name: 'Perca', emoji: '🐠', category: 'pez', rarity: 'poco_comun', sellPrice: 55, description: 'Rayada y desconfiada.' },
  { id: 'surubi', name: 'Surubí', emoji: '🐟', category: 'pez', rarity: 'raro', sellPrice: 130, description: 'Manchado como un jaguar.' },
  { id: 'anguila_plateada', name: 'Anguila plateada', emoji: '🐍', category: 'pez', rarity: 'epico', sellPrice: 440, description: 'Se escurre entre los dedos y entre las leyendas.' },
  // Aguas del delta (nivel 20)
  { id: 'pacu', name: 'Pacú', emoji: '🐟', category: 'pez', rarity: 'comun', sellPrice: 70, description: 'Dientes sospechosamente humanos.' },
  { id: 'dorado', name: 'Dorado', emoji: '🐠', category: 'pez', rarity: 'comun', sellPrice: 75, description: 'El tigre del río.' },
  { id: 'boga', name: 'Boga', emoji: '🐟', category: 'pez', rarity: 'poco_comun', sellPrice: 175, description: 'Pelea hasta el final.' },
  { id: 'manguruyu', name: 'Manguruyú', emoji: '🐡', category: 'pez', rarity: 'raro', sellPrice: 420, description: 'Un gigante del fondo del delta.' },
  { id: 'tortuga_delta', name: 'Tortuga del delta', emoji: '🐢', category: 'pez', rarity: 'epico', sellPrice: 1400, description: 'Se deja atrapar solo si quiere.' },
  // Aguas del mar abierto (nivel 36)
  { id: 'caballa', name: 'Caballa', emoji: '🐟', category: 'pez', rarity: 'comun', sellPrice: 100, description: 'Viaja en cardúmenes enormes.' },
  { id: 'calamar', name: 'Calamar', emoji: '🦑', category: 'pez', rarity: 'comun', sellPrice: 105, description: 'Tinta incluida.' },
  { id: 'langosta', name: 'Langosta', emoji: '🦞', category: 'pez', rarity: 'poco_comun', sellPrice: 250, description: 'Armadura de lujo.' },
  { id: 'atun_rojo', name: 'Atún rojo', emoji: '🐠', category: 'pez', rarity: 'raro', sellPrice: 600, description: 'Músculo puro.' },
  { id: 'tiburon_azul', name: 'Tiburón azul', emoji: '🦈', category: 'pez', rarity: 'epico', sellPrice: 2000, description: 'No es buena idea subirlo al bote.' },
  { id: 'pez_luna', name: 'Pez luna colosal', emoji: '🐡', category: 'pez', rarity: 'legendario', sellPrice: 7000, description: 'Toma sol en la superficie una vez por década.' },
  // Aguas de la fosa (nivel 58)
  { id: 'pez_linterna', name: 'Pez linterna', emoji: '🐡', category: 'pez', rarity: 'comun', sellPrice: 520, description: 'Su propia luz en la oscuridad.' },
  { id: 'calamar_gigante', name: 'Calamar gigante', emoji: '🦑', category: 'pez', rarity: 'poco_comun', sellPrice: 1300, description: 'Ojos del tamaño de un plato.' },
  { id: 'pulpo_dumbo', name: 'Pulpo dumbo', emoji: '🐙', category: 'pez', rarity: 'raro', sellPrice: 3100, description: 'Orejas que parecen aletas.' },
  { id: 'medusa_abisal', name: 'Medusa abisal', emoji: '🪼', category: 'pez', rarity: 'epico', sellPrice: 10000, description: 'Una lámpara viva.' },
  { id: 'celacanto', name: 'Celacanto', emoji: '🐟', category: 'pez', rarity: 'legendario', sellPrice: 32000, description: 'Un fósil que se niega a extinguirse.' },
  { id: 'leviatan_cristal', name: 'Leviatán de cristal', emoji: '🐋', category: 'pez', rarity: 'mitico', sellPrice: 130000, description: 'Transparente. Inmenso. Real.' },
  // ── Carnada, potenciadores y materiales ──────────────────────────
  { id: 'lombriz', name: 'Carnada (lombriz)', emoji: '🪱', category: 'cebo', rarity: 'comun', sellPrice: 1, description: 'Cada línea de pesca usa una. Sale al remover la tierra o se compra en el Mercado.' },
  { id: 'cebo_maiz', name: 'Masa de maíz', emoji: '🌽', category: 'cebo', rarity: 'poco_comun', sellPrice: 0, description: 'Activa "Carnada rendidora": tus líneas gastan menos carnada.' },
  { id: 'cebo_brillante', name: 'Señuelo brillante', emoji: '💠', category: 'cebo', rarity: 'raro', sellPrice: 0, description: 'Activa "Destello": más suerte al pescar.' },
  { id: 'cebo_calamar', name: 'Festín de calamar', emoji: '🦐', category: 'cebo', rarity: 'raro', sellPrice: 0, description: 'Activa "Festín": más XP de pesca.' },
  { id: 'esencia_marea', name: 'Esencia de marea', emoji: '🫧', category: 'cebo', rarity: 'epico', sellPrice: 0, description: 'Activa "Marea alta": una línea extra. No se vende en ningún lado.' },
  { id: 'reloj_arena', name: 'Reloj de arena mojada', emoji: '⏳', category: 'consumible', rarity: 'epico', sellPrice: 0, description: 'Activa "Manos rápidas": menos espera entre pescas.' },
  { id: 'mate', name: 'Mate cebado', emoji: '🧉', category: 'consumible', rarity: 'comun', sellPrice: 0, description: 'Recupera vigor.' },
  { id: 'tonico', name: 'Tónico de raíz', emoji: '🧪', category: 'consumible', rarity: 'raro', sellPrice: 0, description: 'Recupera mucho vigor.' },
  { id: 'abono_algas', name: 'Abono de algas', emoji: '🌿', category: 'consumible', rarity: 'poco_comun', sellPrice: 25, description: 'Se saca del agua; fertiliza la tierra. Mejora las próximas cosechas.' },
  { id: 'mapa_corrientes', name: 'Mapa de corrientes', emoji: '🗺️', category: 'reliquia', rarity: 'legendario', sellPrice: 15000, description: 'Necesario para fabricar la Caña del abismo.' },
];

export const DEFAULT_CONFIG: GameConfig = {
  timezoneOffsetMinutes: -180,
  currency: { name: 'monedas', emoji: '🪙' },
  starter: { coins: 150, items: [{ itemId: 'lombriz', qty: 25 }, { itemId: 'mate', qty: 2 }] },
  maxFertilizerCharges: 30,
  rarities: {
    comun: { label: 'Común', emoji: '⚪', color: 0x95a5a6, rank: 0, marketScale: 2500 },
    poco_comun: { label: 'No común', emoji: '🟢', color: 0x2ecc71, rank: 1, marketScale: 1200 },
    raro: { label: 'Raro', emoji: '🔵', color: 0x3498db, rank: 2, marketScale: 400 },
    epico: { label: 'Épico', emoji: '🟣', color: 0x9b59b6, rank: 3, marketScale: 120 },
    legendario: { label: 'Legendario', emoji: '🟠', color: 0xf39c12, rank: 4, marketScale: 40 },
    mitico: { label: 'Ultralegendario', emoji: '🌟', color: 0xe91e63, rank: 5, marketScale: 15 },
  },
  items,
  consumables: [
    { itemId: 'mate', buyPrice: 250, dailyUseLimit: 4, minTotalLevel: 2, effect: { type: 'vigor', amount: 35 } },
    { itemId: 'tonico', buyPrice: 2200, dailyUseLimit: 2, minTotalLevel: 30, effect: { type: 'vigor', amount: 90 } },
    { itemId: 'abono_algas', buyPrice: null, dailyUseLimit: null, minTotalLevel: 1, effect: { type: 'abono', charges: 5 } },
    // Potenciadores: el precio crece con el nivel total y tienen límite diario de uso.
    { itemId: 'cebo_maiz', buyPrice: 300, dailyUseLimit: 3, minTotalLevel: 5, levelScaling: 0.04, effect: { type: 'buff', buffId: 'rendidora' } },
    { itemId: 'cebo_brillante', buyPrice: 700, dailyUseLimit: 3, minTotalLevel: 10, levelScaling: 0.05, effect: { type: 'buff', buffId: 'destello' } },
    { itemId: 'cebo_calamar', buyPrice: 900, dailyUseLimit: 2, minTotalLevel: 15, levelScaling: 0.05, effect: { type: 'buff', buffId: 'festin' } },
    { itemId: 'esencia_marea', buyPrice: null, dailyUseLimit: 2, minTotalLevel: 10, effect: { type: 'buff', buffId: 'marea_alta' } },
    { itemId: 'reloj_arena', buyPrice: null, dailyUseLimit: 2, minTotalLevel: 10, effect: { type: 'buff', buffId: 'manos_rapidas' } },
  ],
  equipment: [
    {
      slot: 'herramienta', label: 'Herramienta', emoji: '⛏️', skill: 'granja',
      tiers: [
        { tier: 0, name: 'Azada de madera', emoji: '🪵', price: 0, skill: 'granja', level: 1, stats: { yieldMult: 1 } },
        { tier: 1, name: 'Azada de hierro', emoji: '⛏️', price: 1500, skill: 'granja', level: 5, stats: { yieldMult: 1.15 } },
        { tier: 2, name: 'Rastrillo templado', emoji: '🔱', price: 12000, skill: 'granja', level: 15, stats: { yieldMult: 1.35, extraRolls: 1 } },
        { tier: 3, name: 'Hoz rúnica', emoji: '🌙', price: 70000, skill: 'granja', level: 30, stats: { yieldMult: 1.6, extraRolls: 1 } },
        { tier: 4, name: 'Guadaña de cuarzo', emoji: '💎', price: 320000, skill: 'granja', level: 50, stats: { yieldMult: 1.9, extraRolls: 2 } },
        { tier: 5, name: 'Arado estelar', emoji: '🌠', price: 1200000, skill: 'granja', level: 75, stats: { yieldMult: 2.3, extraRolls: 2 } },
      ],
    },
    {
      slot: 'accesorio', label: 'Accesorio', emoji: '🎒', skill: 'granja',
      tiers: [
        { tier: 0, name: 'Sin accesorio', emoji: '▫️', price: 0, skill: 'granja', level: 1, stats: {} },
        { tier: 1, name: 'Sombrero de paja', emoji: '👒', price: 800, skill: 'granja', level: 3, stats: { vigorDiscount: 0.05 } },
        { tier: 2, name: 'Guantes de cuero', emoji: '🧤', price: 9000, skill: 'granja', level: 12, stats: { vigorDiscount: 0.1, rareBonus: 0.1 } },
        { tier: 3, name: 'Pañuelo del alba', emoji: '🧣', price: 60000, skill: 'granja', level: 28, stats: { vigorDiscount: 0.15, rareBonus: 0.25 } },
        { tier: 4, name: 'Amuleto de raíz', emoji: '🧿', price: 280000, skill: 'granja', level: 48, stats: { vigorDiscount: 0.2, rareBonus: 0.45 } },
      ],
    },
  ],
  farming: {
    zones: [
      {
        id: 'huerta', name: 'Huerta del Valle', emoji: '🌱', description: 'Tierra blanda y generosa. Todo empieza acá.',
        level: 1, unlockCost: 0, unlockItems: [], minToolTier: 0, vigorCost: 8, baseXp: 12, rolls: 2,
        crops: [
          { itemId: 'zanahoria', weight: 35, min: 1, max: 3 },
          { itemId: 'papa', weight: 35, min: 1, max: 4 },
          { itemId: 'lechuga', weight: 22, min: 1, max: 2 },
          { itemId: 'ajo', weight: 8, min: 1, max: 2 },
        ],
        rareDrops: [{ itemId: 'lombriz', chance: 0.6 }, { itemId: 'trebol', chance: 0.012 }],
      },
      {
        id: 'invernadero', name: 'Invernadero', emoji: '🏡', description: 'Calor constante y cultivos delicados.',
        level: 8, unlockCost: 2500, unlockItems: [], minToolTier: 1, vigorCost: 10, baseXp: 35, rolls: 2,
        crops: [
          { itemId: 'tomate', weight: 38, min: 1, max: 3 },
          { itemId: 'pimiento', weight: 34, min: 1, max: 3 },
          { itemId: 'frutilla', weight: 20, min: 1, max: 3 },
          { itemId: 'orquidea', weight: 3, min: 1, max: 1 },
          { itemId: 'lechuga', weight: 5, min: 2, max: 4 },
        ],
        rareDrops: [{ itemId: 'lombriz', chance: 0.5 }, { itemId: 'semilla_ambar', chance: 0.006 }],
      },
      {
        id: 'terrazas', name: 'Terrazas de Altura', emoji: '⛰️', description: 'Escalones de tierra entre las nubes.',
        level: 20, unlockCost: 18000, unlockItems: [{ itemId: 'semilla_ambar', qty: 1 }], minToolTier: 2, vigorCost: 12, baseXp: 95, rolls: 2,
        crops: [
          { itemId: 'te_verde', weight: 38, min: 1, max: 3 },
          { itemId: 'quinoa', weight: 36, min: 2, max: 4 },
          { itemId: 'cafe', weight: 22, min: 1, max: 2 },
          { itemId: 'azafran', weight: 4, min: 1, max: 1 },
        ],
        rareDrops: [{ itemId: 'lombriz', chance: 0.4 }, { itemId: 'flor_altura', chance: 0.005 }],
      },
      {
        id: 'bosque', name: 'Bosque Frutal', emoji: '🌳', description: 'Árboles viejos que guardan secretos bajo las raíces.',
        level: 35, unlockCost: 90000, unlockItems: [{ itemId: 'flor_altura', qty: 1 }], minToolTier: 3, vigorCost: 14, baseXp: 250, rolls: 2,
        crops: [
          { itemId: 'manzana', weight: 38, min: 1, max: 3 },
          { itemId: 'nuez', weight: 36, min: 1, max: 3 },
          { itemId: 'miel', weight: 22, min: 1, max: 2 },
          { itemId: 'trufa', weight: 4, min: 1, max: 1 },
        ],
        rareDrops: [{ itemId: 'lombriz', chance: 0.35 }, { itemId: 'semilla_lunar', chance: 0.0035 }],
      },
      {
        id: 'jardin_lunar', name: 'Jardín Lunar', emoji: '🌙', description: 'Un jardín que solo existe de noche.',
        level: 55, unlockCost: 400000, unlockItems: [{ itemId: 'semilla_lunar', qty: 1 }], minToolTier: 4, vigorCost: 16, baseXp: 640, rolls: 2,
        crops: [
          { itemId: 'lirio_plata', weight: 55, min: 1, max: 3 },
          { itemId: 'calabaza_astral', weight: 38, min: 1, max: 2 },
          { itemId: 'fruto_eclipse', weight: 7, min: 1, max: 1 },
        ],
        rareDrops: [{ itemId: 'lombriz', chance: 0.3 }, { itemId: 'brote_celestial', chance: 0.0015 }],
      },
    ],
  },
  fishing: {
    baitItemId: 'lombriz',
    // Probabilidad base por tirada (suman 100): 60 / 26 / 10 / 3,2 / 0,75 / 0,05 %.
    rarityWeights: { comun: 60, poco_comun: 26, raro: 10, epico: 3.2, legendario: 0.75, mitico: 0.05 },
    luckScaling: { comun: 0, poco_comun: 0.5, raro: 1, epico: 1.5, legendario: 2, mitico: 2.5 },
    // Cada "agua" nueva suma peces más valiosos; los viejos siguen apareciendo (con menos peso).
    fish: [
      { itemId: 'mojarra', minLevel: 1, weight: 10, minKg: 0.05, maxKg: 0.3, xp: 30 },
      { itemId: 'bagrecito', minLevel: 1, weight: 10, minKg: 0.2, maxKg: 1.2, xp: 36 },
      { itemId: 'bota_vieja', minLevel: 1, weight: 5, minKg: 0.4, maxKg: 1.1, xp: 9 },
      { itemId: 'cangrejo_rio', minLevel: 1, weight: 10, minKg: 0.1, maxKg: 0.5, xp: 54 },
      { itemId: 'trucha_arcoiris', minLevel: 1, weight: 10, minKg: 0.8, maxKg: 4, xp: 105 },
      { itemId: 'bagre_albino', minLevel: 1, weight: 10, minKg: 1, maxKg: 6, xp: 240 },
      { itemId: 'esturion_dorado', minLevel: 1, weight: 10, minKg: 20, maxKg: 120, xp: 600 },
      { itemId: 'koi_eclipse', minLevel: 1, weight: 10, minKg: 2, maxKg: 9, xp: 1800 },
      { itemId: 'pejerrey', minLevel: 8, weight: 14, minKg: 0.2, maxKg: 1, xp: 90 },
      { itemId: 'carpa', minLevel: 8, weight: 14, minKg: 1, maxKg: 8, xp: 102 },
      { itemId: 'perca', minLevel: 8, weight: 14, minKg: 0.5, maxKg: 3, xp: 162 },
      { itemId: 'surubi', minLevel: 8, weight: 14, minKg: 5, maxKg: 30, xp: 315 },
      { itemId: 'anguila_plateada', minLevel: 8, weight: 14, minKg: 1, maxKg: 6, xp: 720 },
      { itemId: 'pacu', minLevel: 20, weight: 18, minKg: 1, maxKg: 9, xp: 225 },
      { itemId: 'dorado', minLevel: 20, weight: 18, minKg: 2, maxKg: 12, xp: 240 },
      { itemId: 'boga', minLevel: 20, weight: 18, minKg: 1, maxKg: 6, xp: 405 },
      { itemId: 'manguruyu', minLevel: 20, weight: 18, minKg: 15, maxKg: 80, xp: 786 },
      { itemId: 'tortuga_delta', minLevel: 20, weight: 18, minKg: 3, maxKg: 20, xp: 1800 },
      { itemId: 'caballa', minLevel: 36, weight: 22, minKg: 0.3, maxKg: 2, xp: 450 },
      { itemId: 'calamar', minLevel: 36, weight: 22, minKg: 0.5, maxKg: 3, xp: 480 },
      { itemId: 'langosta', minLevel: 36, weight: 22, minKg: 0.5, maxKg: 4, xp: 810 },
      { itemId: 'atun_rojo', minLevel: 36, weight: 22, minKg: 30, maxKg: 250, xp: 1575 },
      { itemId: 'tiburon_azul', minLevel: 36, weight: 22, minKg: 40, maxKg: 200, xp: 3600 },
      { itemId: 'pez_luna', minLevel: 36, weight: 22, minKg: 200, maxKg: 1000, xp: 9000 },
      { itemId: 'pez_linterna', minLevel: 58, weight: 34, minKg: 0.1, maxKg: 1, xp: 960 },
      { itemId: 'calamar_gigante', minLevel: 58, weight: 34, minKg: 50, maxKg: 300, xp: 1728 },
      { itemId: 'pulpo_dumbo', minLevel: 58, weight: 34, minKg: 1, maxKg: 7, xp: 3360 },
      { itemId: 'medusa_abisal', minLevel: 58, weight: 34, minKg: 0.5, maxKg: 4, xp: 7680 },
      { itemId: 'celacanto', minLevel: 58, weight: 34, minKg: 20, maxKg: 90, xp: 19200 },
      { itemId: 'leviatan_cristal', minLevel: 58, weight: 34, minKg: 300, maxKg: 1200, xp: 57600 },
    ],
    extraDrops: [
      { itemId: 'abono_algas', chance: 0.05 },
      { itemId: 'reloj_arena', chance: 0.004 },
      { itemId: 'esencia_marea', chance: 0.003 },
      { itemId: 'mapa_corrientes', chance: 0.0015 },
    ],
    collectionRewards: { comun: 1500, poco_comun: 5000, raro: 20000, epico: 60000, legendario: 150000, mitico: 400000 },
    // El lago: elegís dónde tirar. Después de cada tiro los peces se mueven y el lago cambia.
    lakeSize: 12,
    tiles: [
      { id: 'agua', name: 'Agua', emoji: '🌊', description: 'Pesca normal.', weight: 62, luck: 0 },
      { id: 'burbujas', name: 'Burbujas', emoji: '🫧', description: '+25% de suerte y +10% de XP: algo se mueve abajo.', weight: 18, luck: 0.25, xpMult: 1.1 },
      { id: 'algas', name: 'Algas', emoji: '🌿', description: 'Menos suerte, pero 35% de sacar abono de algas.', weight: 10, luck: -0.1, extraDrops: [{ itemId: 'abono_algas', chance: 0.35 }] },
      { id: 'roca', name: 'Roca', emoji: '🪨', description: '+10% de suerte y chance de objetos perdidos.', weight: 7, luck: 0.1, extraDrops: [{ itemId: 'reloj_arena', chance: 0.02 }, { itemId: 'mapa_corrientes', chance: 0.004 }] },
      { id: 'remolino', name: 'Remolino', emoji: '🌀', description: 'Suerte enorme y Ultralegendario ×2… pero 35% de que se corte cada línea.', weight: 3, maxPerLake: 1, luck: 0.8, ultraMult: 2, snapChance: 0.35 },
    ],
    // 12 cañas. Cada paso sube como mucho +1 línea y +0,08 de suerte; los precios crecen ~×2 y piden más nivel.
    // Algunas se especializan (ahorro, velocidad, suerte) para que no haya una sola "mejor" hasta el final.
    rods: [
      { id: 'junco', name: 'Caña de junco', emoji: '🎋', sprite: 'junco', description: 'Hecha a mano a la orilla del arroyo.', price: 0, fishLevel: 1, requires: [], lines: 1, luck: 0, baitSave: 0, cooldownSeconds: 12 },
      { id: 'corcho', name: 'Caña de corcho', emoji: '🪵', sprite: 'corcho', description: 'Liviana y noble: desperdicia menos carnada.', price: 800, fishLevel: 3, requires: [], lines: 1, luck: 0.03, baitSave: 0.08, cooldownSeconds: 11 },
      { id: 'sauce', name: 'Vara de sauce llorón', emoji: '🌿', sprite: 'sauce', description: 'Flexible: permite tirar dos líneas.', price: 2000, fishLevel: 5, requires: [], lines: 2, luck: 0.03, baitSave: 0, cooldownSeconds: 13 },
      { id: 'tejedora', name: 'Caña tejedora', emoji: '🕸️', sprite: 'tejedora', description: 'Su hilo fino ahorra carnada.', price: 6000, fishLevel: 9, requires: [], lines: 2, luck: 0.06, baitSave: 0.12, cooldownSeconds: 12 },
      { id: 'boya_roja', name: 'Caña boya roja', emoji: '🔴', sprite: 'boya_roja', description: 'Especialista en ahorro: 1 de cada 5 líneas no gasta carnada.', price: 15000, fishLevel: 14, requires: [], lines: 2, luck: 0.09, baitSave: 0.2, cooldownSeconds: 11 },
      { id: 'coral', name: 'Caña de coral', emoji: '🪸', sprite: 'coral', description: 'Tres líneas y buen ojo para lo raro.', price: 35000, fishLevel: 19, requires: [], lines: 3, luck: 0.1, baitSave: 0.08, cooldownSeconds: 12 },
      { id: 'marea_azul', name: 'Caña marea azul', emoji: '🌊', sprite: 'marea_azul', description: 'Equilibrada: suerte y ahorro en la misma vara.', price: 70000, fishLevel: 25, requires: [], lines: 3, luck: 0.14, baitSave: 0.12, cooldownSeconds: 11 },
      { id: 'relampago', name: 'Caña relámpago', emoji: '⚡', sprite: 'relampago', description: 'La más rápida del valle, aunque menos afortunada.', price: 120000, fishLevel: 30, requires: [], lines: 3, luck: 0.12, baitSave: 0.1, cooldownSeconds: 7 },
      { id: 'camuflaje', name: 'Caña sigilo del juncal', emoji: '🍃', sprite: 'camuflaje', description: 'Los peces grandes no la ven venir: cuatro líneas.', price: 220000, fishLevel: 37, requires: [], lines: 4, luck: 0.18, baitSave: 0.12, cooldownSeconds: 11 },
      { id: 'brujula', name: 'Caña brújula de marea', emoji: '🧭', sprite: 'brujula', description: 'A veces una línea trae dos peces (eco).', price: 400000, fishLevel: 45, requires: [], lines: 4, luck: 0.22, baitSave: 0.15, cooldownSeconds: 10, special: { kind: 'eco', chance: 0.04 } },
      { id: 'abismo', name: 'Caña del abismo', emoji: '🕳️', sprite: 'abismo', description: 'Llama a lo ultralegendario (×1,6). Se fabrica con un Mapa de corrientes.', price: 800000, fishLevel: 55, requires: [{ itemId: 'mapa_corrientes', qty: 1 }], lines: 5, luck: 0.26, baitSave: 0.15, cooldownSeconds: 11, special: { kind: 'abismo', ultraMult: 1.6 } },
      { id: 'astro', name: 'Caña del astro hundido', emoji: '🌠', sprite: 'astro', description: 'La obra maestra. Se fabrica con un Celacanto.', price: 1800000, fishLevel: 70, requires: [{ itemId: 'celacanto', qty: 1 }], lines: 5, luck: 0.3, baitSave: 0.2, cooldownSeconds: 9, special: { kind: 'eco', chance: 0.06 } },
    ],
  },
  buffs: [
    { id: 'rendidora', name: 'Carnada rendidora', emoji: '🌽', description: '+25% de probabilidad de no gastar carnada.', minutes: 30, maxMinutes: 90, effect: { baitSave: 0.25 } },
    { id: 'destello', name: 'Destello', emoji: '💠', description: '+15% de suerte al pescar.', minutes: 20, maxMinutes: 60, effect: { luck: 0.15 } },
    { id: 'festin', name: 'Festín', emoji: '🦐', description: '+50% de XP de pesca.', minutes: 30, maxMinutes: 90, effect: { xpMult: 0.5 } },
    { id: 'marea_alta', name: 'Marea alta', emoji: '🫧', description: '+1 línea simultánea.', minutes: 15, maxMinutes: 30, effect: { extraLines: 1 } },
    { id: 'manos_rapidas', name: 'Manos rápidas', emoji: '⏳', description: '−40% de espera entre pescas.', minutes: 20, maxMinutes: 40, effect: { cooldownMult: 0.6 } },
    { id: 'rebaja', name: 'Rebaja del mercado', emoji: '🏷️', description: '−15% en todas las compras del Mercado.', minutes: 60, maxMinutes: 60, effect: { shopDiscount: 0.15 } },
    { id: 'marea_dorada', name: 'Marea dorada', emoji: '🌅', description: 'Evento de servidor: +25% de suerte y +25% de XP para todos.', minutes: 20, maxMinutes: 40, effect: { luck: 0.25, xpMult: 0.25 } },
  ],
  events: {
    guildBoostBuffId: 'marea_dorada',
    rewards: [
      { id: 'monedas', label: 'Bolsa de monedas', emoji: '💰', weight: 24, kind: 'coins', min: 300, max: 900, scalePerLevel: 0.05 },
      { id: 'carnada', label: 'Balde de carnada', emoji: '🪱', weight: 24, kind: 'bait', min: 20, max: 45 },
      { id: 'destello', label: 'Destello (suerte)', emoji: '💠', weight: 12, kind: 'buff', buffId: 'destello', min: 1, max: 1 },
      { id: 'festin', label: 'Festín (XP)', emoji: '🦐', weight: 10, kind: 'buff', buffId: 'festin', min: 1, max: 1 },
      { id: 'rebaja', label: 'Rebaja del mercado', emoji: '🏷️', weight: 8, kind: 'buff', buffId: 'rebaja', min: 1, max: 1 },
      { id: 'marea_alta', label: 'Marea alta (+1 línea)', emoji: '🫧', weight: 5, kind: 'buff', buffId: 'marea_alta', min: 1, max: 1 },
      { id: 'manos_rapidas', label: 'Manos rápidas', emoji: '⏳', weight: 5, kind: 'buff', buffId: 'manos_rapidas', min: 1, max: 1 },
      { id: 'xp', label: 'Empujón de experiencia', emoji: '✨', weight: 8, kind: 'xp', min: 0.15, max: 0.3 },
      { id: 'abono', label: 'Bolsa de abono', emoji: '🌿', weight: 6, kind: 'item', itemId: 'abono_algas', min: 3, max: 6 },
      { id: 'esencia', label: 'Esencia de marea', emoji: '🫧', weight: 3, kind: 'item', itemId: 'esencia_marea', min: 1, max: 2 },
      { id: 'mapa', label: 'Mapa de corrientes', emoji: '🗺️', weight: 1, kind: 'item', itemId: 'mapa_corrientes', min: 1, max: 1 },
    ],
  },
  // Logros: cada uno tiene su insignia en assets/badges/<id>.png (pixel art, scripts/pixel-art.py).
  // Recompensas únicas; los puntos de actividad cuentan para las distinciones por actividad.
  achievements: [
    { id: 'primer_pique', name: 'Primer pique', emoji: '🎣', icon: 'hook', tier: 'bronce', category: 'pesca', metric: 'catches', goal: 1, reward: { coins: 50, items: [{ itemId: 'lombriz', qty: 10 }] }, activity: 10, description: 'Pescá tu primer pez.' },
    { id: 'pescador_constante', name: 'Pescador constante', emoji: '🐟', icon: 'fish', tier: 'plata', category: 'pesca', metric: 'catches', goal: 250, reward: { coins: 1500 }, activity: 25, description: 'Atrapá 250 peces.' },
    { id: 'red_llena', name: 'Red llena', emoji: '🥅', icon: 'net', tier: 'oro', category: 'pesca', metric: 'catches', goal: 2500, reward: { coins: 15000 }, activity: 60, description: 'Atrapá 2.500 peces.' },
    { id: 'leyenda_del_muelle', name: 'Leyenda del muelle', emoji: '⚓', icon: 'anchor', tier: 'platino', category: 'pesca', metric: 'catches', goal: 15000, reward: { coins: 80000 }, activity: 120, description: 'Atrapá 15.000 peces.' },
    { id: 'ojo_para_lo_raro', name: 'Ojo para lo raro', emoji: '🔵', icon: 'eye', tier: 'plata', category: 'pesca', metric: 'stat:rare_caught', goal: 25, reward: { coins: 1000 }, activity: 25, description: 'Atrapá 25 peces Raros o mejores.' },
    { id: 'toque_epico', name: 'Toque épico', emoji: '🟣', icon: 'gem', tier: 'oro', category: 'pesca', metric: 'stat:epic_caught', goal: 10, reward: { coins: 8000 }, activity: 60, description: 'Atrapá 10 peces Épicos o mejores.' },
    { id: 'mito_viviente', name: 'Mito viviente', emoji: '🟠', icon: 'crown', tier: 'platino', category: 'pesca', metric: 'stat:legend_caught', goal: 5, reward: { coins: 40000 }, activity: 120, description: 'Atrapá 5 peces Legendarios o mejores.' },
    { id: 'eclipse', name: 'Testigo del eclipse', emoji: '🌟', icon: 'eclipse', tier: 'diamante', category: 'pesca', metric: 'stat:ultra_caught', goal: 1, reward: { coins: 150000 }, activity: 250, description: 'Atrapá un pez Ultralegendario.' },
    { id: 'naturalista', name: 'Naturalista', emoji: '📖', icon: 'book', tier: 'plata', category: 'pesca', metric: 'species', goal: 15, reward: { coins: 4000 }, activity: 25, description: 'Registrá 15 especies distintas.' },
    { id: 'enciclopedia', name: 'Enciclopedia viva', emoji: '📚', icon: 'books', tier: 'diamante', category: 'pesca', metric: 'species', goal: 30, reward: { coins: 100000 }, activity: 250, description: 'Registrá las 30 especies del valle.' },
    { id: 'archivista', name: 'Archivista', emoji: '🗂️', icon: 'scroll', tier: 'oro', category: 'pesca', metric: 'collections', goal: 3, reward: { coins: 20000 }, activity: 60, description: 'Completá 3 colecciones de rareza.' },
    { id: 'primera_cosecha', name: 'Primera cosecha', emoji: '🌱', icon: 'sprout', tier: 'bronce', category: 'granja', metric: 'harvests', goal: 1, reward: { coins: 50 }, activity: 10, description: 'Cosechá por primera vez.' },
    { id: 'manos_de_tierra', name: 'Manos de tierra', emoji: '🌾', icon: 'wheat', tier: 'plata', category: 'granja', metric: 'harvests', goal: 300, reward: { coins: 1500 }, activity: 25, description: 'Cosechá 300 veces.' },
    { id: 'granjero_incansable', name: 'Granjero incansable', emoji: '🚜', icon: 'tractor', tier: 'oro', category: 'granja', metric: 'harvests', goal: 3000, reward: { coins: 15000 }, activity: 60, description: 'Cosechá 3.000 veces.' },
    { id: 'toque_de_oro', name: 'Toque de oro', emoji: '✨', icon: 'sun', tier: 'plata', category: 'granja', metric: 'stat:golden_harvests', goal: 10, reward: { coins: 3000 }, activity: 25, description: 'Conseguí 10 cosechas doradas.' },
    { id: 'rey_del_valle', name: 'Señor de la tierra', emoji: '👑', icon: 'castle', tier: 'platino', category: 'granja', metric: 'farm_level', goal: 50, reward: { coins: 60000 }, activity: 120, description: 'Llegá a nivel 50 de granja.' },
    { id: 'primera_venta', name: 'Primera venta', emoji: '🤝', icon: 'tag', tier: 'bronce', category: 'economia', metric: 'stat:items_sold', goal: 1, reward: { coins: 25 }, activity: 10, description: 'Vendé algo en el Mercado.' },
    { id: 'comerciante', name: 'Comerciante', emoji: '💰', icon: 'coins', tier: 'plata', category: 'economia', metric: 'stat:coins_from_sales', goal: 50000, reward: { coins: 2500 }, activity: 25, description: 'Ganá 50.000 monedas vendiendo.' },
    { id: 'magnate', name: 'Magnate del valle', emoji: '🏦', icon: 'vault', tier: 'oro', category: 'economia', metric: 'stat:coins_from_sales', goal: 1000000, reward: { coins: 40000 }, activity: 60, description: 'Ganá 1.000.000 de monedas vendiendo.' },
    { id: 'cliente_fiel', name: 'Cliente fiel', emoji: '🛒', icon: 'cart', tier: 'plata', category: 'economia', metric: 'stat:purchases', goal: 25, reward: { coins: 1500 }, activity: 25, description: 'Hacé 25 compras en el Mercado.' },
    { id: 'inversor', name: 'Inversor', emoji: '📈', icon: 'chart', tier: 'oro', category: 'economia', metric: 'stat:coins_spent', goal: 500000, reward: { coins: 20000 }, activity: 60, description: 'Invertí 500.000 monedas en el Mercado.' },
    { id: 'aprendiz', name: 'Aprendiz del valle', emoji: '⭐', icon: 'star', tier: 'bronce', category: 'progresion', metric: 'total_level', goal: 20, reward: { coins: 1000 }, activity: 10, description: 'Alcanzá nivel total 20.' },
    { id: 'veterano', name: 'Veterano', emoji: '🌠', icon: 'stars', tier: 'oro', category: 'progresion', metric: 'total_level', goal: 60, reward: { coins: 15000 }, activity: 60, description: 'Alcanzá nivel total 60.' },
    { id: 'maestro', name: 'Maestro del valle', emoji: '🏆', icon: 'trophy', tier: 'platino', category: 'progresion', metric: 'total_level', goal: 120, reward: { coins: 80000 }, activity: 120, description: 'Alcanzá nivel total 120.' },
    { id: 'segunda_cana', name: 'Buena madera', emoji: '🎋', icon: 'rod', tier: 'bronce', category: 'canas', metric: 'rods_owned', goal: 2, reward: { coins: 300, items: [{ itemId: 'lombriz', qty: 20 }] }, activity: 10, description: 'Conseguí tu segunda caña.' },
    { id: 'coleccionista_canas', name: 'Vitrina de cañas', emoji: '🎣', icon: 'rods', tier: 'oro', category: 'canas', metric: 'rods_owned', goal: 6, reward: { coins: 12000 }, activity: 60, description: 'Tené 6 cañas distintas.' },
    { id: 'todas_las_canas', name: 'Arsenal completo', emoji: '🗡️', icon: 'arsenal', tier: 'diamante', category: 'canas', metric: 'rods_owned', goal: 12, reward: { coins: 120000 }, activity: 250, description: 'Tené las 12 cañas del valle.' },
    { id: 'afortunado', name: 'Afortunado', emoji: '🎁', icon: 'gift', tier: 'bronce', category: 'eventos', metric: 'stat:events_won', goal: 1, reward: { coins: 300 }, activity: 10, description: 'Ganá un sorteo.' },
    { id: 'favorito_del_azar', name: 'Favorito del azar', emoji: '🍀', icon: 'clover', tier: 'oro', category: 'eventos', metric: 'stat:events_won', goal: 15, reward: { coins: 10000 }, activity: 60, description: 'Ganá 15 sorteos.' },
  ],
  upgrades: [
    { id: 'vigor_max', name: 'Resistencia', emoji: '💪', description: '+10 de vigor máximo por nivel.', maxLevel: 10, baseCost: 2000, costGrowth: 1.75, baseTotalLevel: 4, totalLevelPerStep: 8, perLevel: 10 },
    { id: 'vigor_regen', name: 'Respiración', emoji: '🌬️', description: 'El vigor se recupera un 8% más rápido por nivel.', maxLevel: 8, baseCost: 3000, costGrowth: 1.8, baseTotalLevel: 6, totalLevelPerStep: 9, perLevel: 0.08 },
    { id: 'suerte', name: 'Buena estrella', emoji: '🍀', description: '+4% de probabilidad de hallazgos raros por nivel (granja y pesca).', maxLevel: 10, baseCost: 5000, costGrowth: 1.9, baseTotalLevel: 10, totalLevelPerStep: 10, perLevel: 0.04 },
    { id: 'negociante', name: 'Buen negociante', emoji: '🤝', description: '+3% al precio de venta por nivel.', maxLevel: 8, baseCost: 4000, costGrowth: 1.85, baseTotalLevel: 8, totalLevelPerStep: 10, perLevel: 0.03 },
  ],
  tuning: {
    vigor: { base: 100, regenSeconds: 45 },
    farm: { cooldownSeconds: 6, xpMultiplier: 1, yieldMultiplier: 1, rareMultiplier: 1, goldenChance: 0.04, fertilizerBonus: 0.4 },
    fatigue: { threshold: 30, perAction: 1, decayPerMinute: 0.5, step: 0.03, floor: 0.35 },
    fish: {
      // Sin espera ni vigor por defecto: se pesca sin límite de clics; la carnada es el único costo.
      xpMultiplier: 1, luckMultiplier: 1, maxLuck: 0.8, vigorPerCast: 0, vigorPerLine: 0,
      cooldownMultiplier: 0, minCooldownSeconds: 0, maxLines: 6, pityThreshold: 120, baitPriceBase: 10, baitPricePerLevel: 1,
    },
    activity: {
      fishPoints: 2, farmPoints: 2, sellPoints: 1, buyPoints: 2, eventPoints: 5, minTradeValue: 50,
      dailyCapFish: 120, dailyCapFarm: 120, dailyCapTrade: 40, dailyCapTotal: 250,
    },
    events: {
      minMinutes: 100, maxMinutes: 140, joinSeconds: 300, maxWinners: 3, boostChance: 0.15, boostMinutes: 20,
      minAccountDays: 14, minMemberHours: 24, minTotalLevel: 3, dailyWinCap: 2,
    },
    market: { buyMultiplier: 1, sellMultiplier: 1, saturationHalfLifeHours: 6, minPriceMultiplier: 0.45 },
    progression: {
      maxLevel: 100, curveBase: 25, curveExponent: 2.2, curveLinear: 20, curveMultiplier: 1,
      levelGapTolerance: 10, levelGapPenalty: 0.07, levelGapFloor: 0.15, levelUpCoinsPerLevel: 40,
    },
    antispam: { actionsPerWindow: 8, windowSeconds: 10, flagThreshold: 5 },
  },
};
